cpp:
  cluster:
    name: SimpleCluster
    master:
      name: Test-Master
      host: 0.0.0.0
      host-name: J
      netty:
        port: 10089
    worker:
      name: Test-Worker

    properties: {
        a: a
    }






